title: SeeSharpCode Projects
author: Melikhaya Mzola
email: melikhayamzola@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog I will be addressing the basics and neglected fundementals of C#. I will be focusing on 
  Data Structures and Design Patterns

# social links
twitter_username: melikhayamzola # DO NOT include the @ character, or else the build will fail!
github_username:  The-CSharp-Legend # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

